---
# tasks file for atb-ansible-ghostagent
- name: Download microsoft repository
  become: true
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/config/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/packages-microsoft-prod.deb"
    dest: "/opt/packages-microsoft-prod.deb"
  tags:
    - install
    - dependencies

- name: Install microsoft repo
  ansible.builtin.apt:
    deb: "/opt/packages-microsoft-prod.deb"
  tags:
    - install
    - dependencies

- name: Install packages for ghost-agent
  become: true
  ansible.builtin.package:
    name: "{{ ghostagent_packages }}"
    update_cache: yes
  tags:
    - install
    - dependencies

- name: Download and unarchive ghosts v8.0.0
  become: true
  become_user: "{{ ghostsagent_user }}"
  ansible.builtin.unarchive:
    src: "https://cmu.box.com/shared/static/tdozbmmdyvajubohwtnon1huyfqjuwrz.zip"
    dest: "/home/{{ ghostsagent_user }}/"
    remote_src: yes
  tags:
    - install
    - ghostagent

- name: Update application.json with the ghostsserver url
  become: true
  become_user: "{{ ghostsagent_user }}"
  ansible.builtin.template:
    src: application.json.j2
    dest: "{{ ghostagent_path }}/config/application.json"
  tags:
    - install
    - ghostagent

- name: Add ghostagent timeline file
  become: true
  become_user: "{{ ghostsagent_user }}"
  ansible.builtin.template:
    src: "{{ ghostagent_timeline_file }}"
    dest: "{{ ghostagent_path }}/config/timeline.json"
  tags:
    - update
    - ghostagent

# Download chrome and chromedriver binaries from: https://googlechromelabs.github.io/chrome-for-testing/
- name: Download google-chrome-stable binary
  become: true
  ansible.builtin.unarchive:
    src: "https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.60/linux64/chrome-linux64.zip"
    dest: "{{ ghostagent_path }}/"
    remote_src: yes
  tags:
    - install
    - chrome

- name: Download and unarchive ChromeDriver
  become: true
  ansible.builtin.unarchive:
    src: "https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.60/linux64/chromedriver-linux64.zip"
    dest: /opt/
    remote_src: yes
  tags:
    - install
    - chrome

- name: Move ChromeDriver to ghosts folder and make it executable
  become: true
  ansible.builtin.shell:
    cmd: "mv /opt/chromedriver-linux64/chromedriver {{ ghostagent_path }}/ && chmod 0755 {{ ghostagent_path }}/chromedriver"
  tags:
    - install
    - chrome

- name: Deploy ghostagent systemd service
  become: true
  ansible.builtin.template:
    src: ghosts.j2
    dest: /etc/systemd/system/ghostagent.service
  tags:
    - start
    - ghostagent

- name: Enable and start ghostagent service
  become: true
  ansible.builtin.service:
    name: ghostagent
    enabled: "{{ ghostagent_autostart }}"
    state: "{{ 'started' if ghostagent_autostart else 'stopped' }}"
  when: ghostagent_autostart
  tags:
    - start
    - ghostagent
