---
# tasks file for atb-ansible-ghostagent
- name: Download microsoft repository
  become: true
  ansible.builtin.shell:
    cmd: "wget https://packages.microsoft.com/config/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/packages-microsoft-prod.deb -O /opt/packages-microsoft-prod.deb"
    creates: "/opt/packages-microsoft-prod.deb"
  tags:
    - install
    - dependencies

- name: Install microsoft repo
  ansible.builtin.apt:
    deb: "/opt/packages-microsoft-prod.deb"
  tags:
    - install
    - dependencies

- name: Install packages for ghost-agent
  become: true
  ansible.builtin.package:
    name: "{{ ghostagent_packages }}"
    update_cache: yes
  tags:
    - install
    - dependencies

- name: Unzip ghosts-agent
  become: true
  become_user: "{{ ghostsagent_user }}"
  ansible.builtin.unarchive:
    src: ghosts.tar.gz
    dest: "{{ ghostagent_path }}"

- name: Download google-chrome-stable
  become: true
  ansible.builtin.shell:
    cmd: "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /opt/google-chrome-stable_current_amd64.deb"
    creates: "/opt/google-chrome-stable_current_amd64.deb"
  tags:
    - install
    - chrome

- name: Install google-chrome-stable
  become: true
  ansible.builtin.apt:
    deb: "/opt/google-chrome-stable_current_amd64.deb"
  tags:
    - install
    - chrome

- name: Get Chrome version
  become: true
  ansible.builtin.shell:
    cmd: "google-chrome --version | grep -oP '[0-9]+.[0-9]+.[0-9]+.[0-9]+'"
  register: chrome_version
  tags:
    - install
    - chrome

- name: Download ChromeDriver
  become: true
  ansible.builtin.shell:
    cmd: "wget https://storage.googleapis.com/chrome-for-testing-public/{{ chrome_version.stdout }}/linux64/chromedriver-linux64.zip -O /opt/chromedriver-linux64.zip"
    creates: "/opt/chromedriver-linux64.zip"
  tags:
    - install
    - chrome

- name: Unzip ChromeDriver
  become: true
  ansible.builtin.unarchive:
    src: /opt/chromedriver-linux64.zip
    dest: /opt/
    remote_src: yes
  tags:
    - install
    - chrome

- name: Move ChromeDriver to /usr/local/bin and make it executable
  become: true
  ansible.builtin.shell:
    cmd: "mv /opt/chromedriver-linux64/chromedriver /usr/local/bin/ && chmod 0755 /usr/local/bin/chromedriver"
  tags:
    - install
    - chrome

